name: Executa MLP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-mlp:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar main.py
      run: |
        python src/main.py

    - name: Upload dos arquivos de saída
      uses: actions/upload-artifact@v4
      with:
        name: arquivos-de-relatorio
        path: |
          hiperparametros.txt
          pesosiniciais.txt
          pesosfinais.txt
          erro.txt
          saidas_teste.txt
